# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigurationDialog(object):
    def setupUi(self, ConfigurationDialog):
        ConfigurationDialog.setObjectName("ConfigurationDialog")
        ConfigurationDialog.resize(612, 426)
        ConfigurationDialog.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gridLayout = QtWidgets.QGridLayout(ConfigurationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(ConfigurationDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.baudLabel = QtWidgets.QLabel(self.groupBox_2)
        self.baudLabel.setObjectName("baudLabel")
        self.horizontalLayout_5.addWidget(self.baudLabel)
        self.baudComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.baudComboBox.setObjectName("baudComboBox")
        self.horizontalLayout_5.addWidget(self.baudComboBox)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.samplFreqLabel = QtWidgets.QLabel(self.groupBox_2)
        self.samplFreqLabel.setObjectName("samplFreqLabel")
        self.horizontalLayout_3.addWidget(self.samplFreqLabel)
        self.samplFreqSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.samplFreqSpinBox.setMinimum(1)
        self.samplFreqSpinBox.setMaximum(1000)
        self.samplFreqSpinBox.setProperty("value", 100)
        self.samplFreqSpinBox.setObjectName("samplFreqSpinBox")
        self.horizontalLayout_3.addWidget(self.samplFreqSpinBox)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.samplIntervalLabel = QtWidgets.QLabel(self.groupBox_2)
        self.samplIntervalLabel.setObjectName("samplIntervalLabel")
        self.horizontalLayout_3.addWidget(self.samplIntervalLabel)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ConfigurationDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addSignalPushButton = QtWidgets.QPushButton(self.groupBox)
        self.addSignalPushButton.setObjectName("addSignalPushButton")
        self.verticalLayout.addWidget(self.addSignalPushButton)
        self.removeSignalPushButton = QtWidgets.QPushButton(self.groupBox)
        self.removeSignalPushButton.setObjectName("removeSignalPushButton")
        self.verticalLayout.addWidget(self.removeSignalPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.dataPathGroupBox = QtWidgets.QGroupBox(ConfigurationDialog)
        self.dataPathGroupBox.setFlat(True)
        self.dataPathGroupBox.setObjectName("dataPathGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dataPathGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathLineEdit = QtWidgets.QLineEdit(self.dataPathGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLineEdit.sizePolicy().hasHeightForWidth())
        self.pathLineEdit.setSizePolicy(sizePolicy)
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout.addWidget(self.pathLineEdit)
        self.pathToolButton = QtWidgets.QToolButton(self.dataPathGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathToolButton.sizePolicy().hasHeightForWidth())
        self.pathToolButton.setSizePolicy(sizePolicy)
        self.pathToolButton.setMaximumSize(QtCore.QSize(28, 16777215))
        self.pathToolButton.setObjectName("pathToolButton")
        self.horizontalLayout.addWidget(self.pathToolButton)
        self.gridLayout.addWidget(self.dataPathGroupBox, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigurationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.buttonBox.raise_()
        self.dataPathGroupBox.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()

        self.retranslateUi(ConfigurationDialog)
        self.buttonBox.accepted.connect(ConfigurationDialog.accept)
        self.buttonBox.rejected.connect(ConfigurationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationDialog)

    def retranslateUi(self, ConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationDialog.setWindowTitle(_translate("ConfigurationDialog", "Configuration"))
        self.groupBox_2.setTitle(_translate("ConfigurationDialog", "Serial communication"))
        self.baudLabel.setText(_translate("ConfigurationDialog", "Baud"))
        self.samplFreqLabel.setText(_translate("ConfigurationDialog", "Sampling frequency (Hz):"))
        self.label.setText(_translate("ConfigurationDialog", "interval (ms):"))
        self.samplIntervalLabel.setText(_translate("ConfigurationDialog", "10.000"))
        self.groupBox.setTitle(_translate("ConfigurationDialog", "Signals"))
        self.addSignalPushButton.setText(_translate("ConfigurationDialog", "Add"))
        self.removeSignalPushButton.setText(_translate("ConfigurationDialog", "Remove"))
        self.dataPathGroupBox.setTitle(_translate("ConfigurationDialog", "Default data path"))
        self.pathToolButton.setText(_translate("ConfigurationDialog", "..."))

