# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigurationDialog(object):
    def setupUi(self, ConfigurationDialog):
        ConfigurationDialog.setObjectName("ConfigurationDialog")
        ConfigurationDialog.resize(351, 401)
        ConfigurationDialog.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gridLayout_3 = QtWidgets.QGridLayout(ConfigurationDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(ConfigurationDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.mainTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.baudLabel = QtWidgets.QLabel(self.groupBox_2)
        self.baudLabel.setObjectName("baudLabel")
        self.gridLayout_2.addWidget(self.baudLabel, 0, 0, 1, 1)
        self.baudComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.baudComboBox.setObjectName("baudComboBox")
        self.gridLayout_2.addWidget(self.baudComboBox, 0, 1, 1, 1)
        self.samplFreqLabel = QtWidgets.QLabel(self.groupBox_2)
        self.samplFreqLabel.setObjectName("samplFreqLabel")
        self.gridLayout_2.addWidget(self.samplFreqLabel, 1, 0, 1, 1)
        self.samplFreqSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.samplFreqSpinBox.setMinimum(1)
        self.samplFreqSpinBox.setMaximum(1000)
        self.samplFreqSpinBox.setProperty("value", 100)
        self.samplFreqSpinBox.setObjectName("samplFreqSpinBox")
        self.gridLayout_2.addWidget(self.samplFreqSpinBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.samplIntervalLabel = QtWidgets.QLabel(self.groupBox_2)
        self.samplIntervalLabel.setObjectName("samplIntervalLabel")
        self.gridLayout_2.addWidget(self.samplIntervalLabel, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.dataPathGroupBox = QtWidgets.QGroupBox(self.mainTab)
        self.dataPathGroupBox.setFlat(True)
        self.dataPathGroupBox.setObjectName("dataPathGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.dataPathGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.dataPathGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.pathLineEdit = QtWidgets.QLineEdit(self.dataPathGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathLineEdit.sizePolicy().hasHeightForWidth())
        self.pathLineEdit.setSizePolicy(sizePolicy)
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.gridLayout.addWidget(self.pathLineEdit, 0, 1, 1, 1)
        self.pathToolButton = QtWidgets.QToolButton(self.dataPathGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathToolButton.sizePolicy().hasHeightForWidth())
        self.pathToolButton.setSizePolicy(sizePolicy)
        self.pathToolButton.setMaximumSize(QtCore.QSize(28, 16777215))
        self.pathToolButton.setObjectName("pathToolButton")
        self.gridLayout.addWidget(self.pathToolButton, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.dataPathGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.flushSecondsSpinBox = QtWidgets.QSpinBox(self.dataPathGroupBox)
        self.flushSecondsSpinBox.setMinimum(1)
        self.flushSecondsSpinBox.setMaximum(600)
        self.flushSecondsSpinBox.setProperty("value", 5)
        self.flushSecondsSpinBox.setObjectName("flushSecondsSpinBox")
        self.gridLayout.addWidget(self.flushSecondsSpinBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.dataPathGroupBox)
        self.tabWidget.addTab(self.mainTab, "")
        self.signalsTab = QtWidgets.QWidget()
        self.signalsTab.setObjectName("signalsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.signalsTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableView(self.signalsTab)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addSignalPushButton = QtWidgets.QPushButton(self.signalsTab)
        self.addSignalPushButton.setObjectName("addSignalPushButton")
        self.horizontalLayout.addWidget(self.addSignalPushButton)
        self.removeSignalPushButton = QtWidgets.QPushButton(self.signalsTab)
        self.removeSignalPushButton.setObjectName("removeSignalPushButton")
        self.horizontalLayout.addWidget(self.removeSignalPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.signalsTab, "")
        self.subjectTab = QtWidgets.QWidget()
        self.subjectTab.setObjectName("subjectTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.subjectTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subjectGroupBox = QtWidgets.QGroupBox(self.subjectTab)
        self.subjectGroupBox.setObjectName("subjectGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.subjectGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.subjectGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.codeLineEdit = QtWidgets.QLineEdit(self.subjectGroupBox)
        self.codeLineEdit.setObjectName("codeLineEdit")
        self.gridLayout_4.addWidget(self.codeLineEdit, 0, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.subjectGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.subjectGroupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout_4.addWidget(self.nameLineEdit, 1, 1, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.subjectGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.dobDateEdit = QtWidgets.QDateEdit(self.subjectGroupBox)
        self.dobDateEdit.setObjectName("dobDateEdit")
        self.gridLayout_4.addWidget(self.dobDateEdit, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.subjectGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 3, 1, 1)
        self.sexComboBox = QtWidgets.QComboBox(self.subjectGroupBox)
        self.sexComboBox.setMaxCount(0)
        self.sexComboBox.setObjectName("sexComboBox")
        self.gridLayout_4.addWidget(self.sexComboBox, 2, 4, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 10)
        self.gridLayout_4.setColumnStretch(3, 1)
        self.gridLayout_4.setColumnStretch(4, 1)
        self.verticalLayout_3.addWidget(self.subjectGroupBox)
        self.recordingGroupBox = QtWidgets.QGroupBox(self.subjectTab)
        self.recordingGroupBox.setObjectName("recordingGroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.recordingGroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.recordingGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.experimentIdLineEdit = QtWidgets.QLineEdit(self.recordingGroupBox)
        self.experimentIdLineEdit.setObjectName("experimentIdLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.experimentIdLineEdit)
        self.label_8 = QtWidgets.QLabel(self.recordingGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.investigatorIdLineEdit = QtWidgets.QLineEdit(self.recordingGroupBox)
        self.investigatorIdLineEdit.setObjectName("investigatorIdLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.investigatorIdLineEdit)
        self.label_9 = QtWidgets.QLabel(self.recordingGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.equipmentCodeLineEdit = QtWidgets.QLineEdit(self.recordingGroupBox)
        self.equipmentCodeLineEdit.setObjectName("equipmentCodeLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.equipmentCodeLineEdit)
        self.verticalLayout_3.addWidget(self.recordingGroupBox)
        self.tabWidget.addTab(self.subjectTab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigurationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ConfigurationDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(ConfigurationDialog.accept)
        self.buttonBox.rejected.connect(ConfigurationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationDialog)

    def retranslateUi(self, ConfigurationDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationDialog.setWindowTitle(_translate("ConfigurationDialog", "Configuration"))
        self.groupBox_2.setTitle(_translate("ConfigurationDialog", "Serial communication"))
        self.baudLabel.setText(_translate("ConfigurationDialog", "Baud"))
        self.samplFreqLabel.setText(_translate("ConfigurationDialog", "Sampling frequency (Hz)"))
        self.label.setText(_translate("ConfigurationDialog", "Sampling interval (ms)"))
        self.samplIntervalLabel.setText(_translate("ConfigurationDialog", "10.000"))
        self.dataPathGroupBox.setTitle(_translate("ConfigurationDialog", "Save data"))
        self.label_6.setText(_translate("ConfigurationDialog", "Default data path"))
        self.pathToolButton.setText(_translate("ConfigurationDialog", "..."))
        self.label_10.setText(_translate("ConfigurationDialog", "Flush to disk every"))
        self.flushSecondsSpinBox.setToolTip(_translate("ConfigurationDialog", "How often are data saved to disk?"))
        self.flushSecondsSpinBox.setSuffix(_translate("ConfigurationDialog", " seconds"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("ConfigurationDialog", "Main"))
        self.addSignalPushButton.setText(_translate("ConfigurationDialog", "Add"))
        self.removeSignalPushButton.setText(_translate("ConfigurationDialog", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signalsTab), _translate("ConfigurationDialog", "Signals"))
        self.subjectGroupBox.setTitle(_translate("ConfigurationDialog", "Subject"))
        self.label_2.setText(_translate("ConfigurationDialog", "Code"))
        self.codeLineEdit.setToolTip(_translate("ConfigurationDialog", "Subject ID"))
        self.label_5.setText(_translate("ConfigurationDialog", "Name"))
        self.nameLineEdit.setToolTip(_translate("ConfigurationDialog", "Subject name"))
        self.label_4.setText(_translate("ConfigurationDialog", "DoB"))
        self.dobDateEdit.setToolTip(_translate("ConfigurationDialog", "Date of birth"))
        self.dobDateEdit.setDisplayFormat(_translate("ConfigurationDialog", "yyyy-MM-dd"))
        self.label_3.setText(_translate("ConfigurationDialog", "Sex"))
        self.recordingGroupBox.setTitle(_translate("ConfigurationDialog", "Recording"))
        self.label_7.setText(_translate("ConfigurationDialog", "Experiment ID"))
        self.experimentIdLineEdit.setToolTip(_translate("ConfigurationDialog", "Code of the experiment/investigation"))
        self.label_8.setText(_translate("ConfigurationDialog", "Investigator ID"))
        self.investigatorIdLineEdit.setToolTip(_translate("ConfigurationDialog", "Code of responsible investigator"))
        self.label_9.setText(_translate("ConfigurationDialog", "Equipment code"))
        self.equipmentCodeLineEdit.setToolTip(_translate("ConfigurationDialog", "Code of equipment used"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.subjectTab), _translate("ConfigurationDialog", "Subject/Rec"))

