# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SignalDialog(object):
    def setupUi(self, SignalDialog):
        SignalDialog.setObjectName("SignalDialog")
        SignalDialog.setWindowModality(QtCore.Qt.WindowModal)
        SignalDialog.resize(321, 403)
        self.gridLayout = QtWidgets.QGridLayout(SignalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLabel = QtWidgets.QLabel(SignalDialog)
        self.labelLabel.setObjectName("labelLabel")
        self.gridLayout.addWidget(self.labelLabel, 0, 0, 1, 2)
        self.labelLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.labelLineEdit.setMaxLength(16)
        self.labelLineEdit.setObjectName("labelLineEdit")
        self.gridLayout.addWidget(self.labelLineEdit, 0, 2, 1, 1)
        self.transducerLabel = QtWidgets.QLabel(SignalDialog)
        self.transducerLabel.setObjectName("transducerLabel")
        self.gridLayout.addWidget(self.transducerLabel, 1, 0, 1, 2)
        self.transducerLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.transducerLineEdit.setObjectName("transducerLineEdit")
        self.gridLayout.addWidget(self.transducerLineEdit, 1, 2, 1, 1)
        self.physDimLabel = QtWidgets.QLabel(SignalDialog)
        self.physDimLabel.setObjectName("physDimLabel")
        self.gridLayout.addWidget(self.physDimLabel, 2, 0, 1, 2)
        self.physicalDimLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.physicalDimLineEdit.setMaxLength(8)
        self.physicalDimLineEdit.setObjectName("physicalDimLineEdit")
        self.gridLayout.addWidget(self.physicalDimLineEdit, 2, 2, 1, 1)
        self.physMinLabel = QtWidgets.QLabel(SignalDialog)
        self.physMinLabel.setObjectName("physMinLabel")
        self.gridLayout.addWidget(self.physMinLabel, 3, 0, 1, 2)
        self.physicalMinLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.physicalMinLineEdit.setMaxLength(8)
        self.physicalMinLineEdit.setObjectName("physicalMinLineEdit")
        self.gridLayout.addWidget(self.physicalMinLineEdit, 3, 2, 1, 1)
        self.physMaxLabel = QtWidgets.QLabel(SignalDialog)
        self.physMaxLabel.setObjectName("physMaxLabel")
        self.gridLayout.addWidget(self.physMaxLabel, 4, 0, 1, 2)
        self.physicalMaxLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.physicalMaxLineEdit.setMaxLength(8)
        self.physicalMaxLineEdit.setObjectName("physicalMaxLineEdit")
        self.gridLayout.addWidget(self.physicalMaxLineEdit, 4, 2, 1, 1)
        self.digMinLabel = QtWidgets.QLabel(SignalDialog)
        self.digMinLabel.setObjectName("digMinLabel")
        self.gridLayout.addWidget(self.digMinLabel, 5, 0, 1, 2)
        self.digitalMinLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.digitalMinLineEdit.setMaxLength(8)
        self.digitalMinLineEdit.setObjectName("digitalMinLineEdit")
        self.gridLayout.addWidget(self.digitalMinLineEdit, 5, 2, 1, 1)
        self.digMaxLabel = QtWidgets.QLabel(SignalDialog)
        self.digMaxLabel.setObjectName("digMaxLabel")
        self.gridLayout.addWidget(self.digMaxLabel, 6, 0, 1, 2)
        self.digitalMaxLineEdit = QtWidgets.QLineEdit(SignalDialog)
        self.digitalMaxLineEdit.setMaxLength(8)
        self.digitalMaxLineEdit.setObjectName("digitalMaxLineEdit")
        self.gridLayout.addWidget(self.digitalMaxLineEdit, 6, 2, 1, 1)
        self.prefilteringLabel = QtWidgets.QLabel(SignalDialog)
        self.prefilteringLabel.setObjectName("prefilteringLabel")
        self.gridLayout.addWidget(self.prefilteringLabel, 7, 0, 1, 1)
        self.prefilteringTextEdit = QtWidgets.QPlainTextEdit(SignalDialog)
        self.prefilteringTextEdit.setObjectName("prefilteringTextEdit")
        self.gridLayout.addWidget(self.prefilteringTextEdit, 7, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SignalDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 1, 1, 2)

        self.retranslateUi(SignalDialog)
        self.buttonBox.accepted.connect(SignalDialog.accept)
        self.buttonBox.rejected.connect(SignalDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SignalDialog)

    def retranslateUi(self, SignalDialog):
        _translate = QtCore.QCoreApplication.translate
        SignalDialog.setWindowTitle(_translate("SignalDialog", "Signal"))
        self.labelLabel.setText(_translate("SignalDialog", "Label"))
        self.transducerLabel.setText(_translate("SignalDialog", "Transducer type"))
        self.physDimLabel.setText(_translate("SignalDialog", "Physical dimensions"))
        self.physMinLabel.setText(_translate("SignalDialog", "Physical minimum"))
        self.physicalMinLineEdit.setText(_translate("SignalDialog", "-1"))
        self.physMaxLabel.setText(_translate("SignalDialog", "Physical maximum"))
        self.physicalMaxLineEdit.setText(_translate("SignalDialog", "1"))
        self.digMinLabel.setText(_translate("SignalDialog", "Digital minimum"))
        self.digitalMinLineEdit.setText(_translate("SignalDialog", "-1"))
        self.digMaxLabel.setText(_translate("SignalDialog", "Digital maximum"))
        self.digitalMaxLineEdit.setText(_translate("SignalDialog", "1"))
        self.prefilteringLabel.setText(_translate("SignalDialog", "Prefiltering"))

